name: Regression Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  python-regression-serial:
    name: Python regression (serial)
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip

      - name: Show environment info
        run: |
          pwd
          ls
          python --version
          pip --version

      - name: Set up MPI
        uses: mpi4py/setup-mpi@v1

      - name: Install mpi4py
        run: |
          pip install --upgrade pip
          pip install --no-binary=mpi4py mpi4py

      - name: Install MC/DC
        run: |
          pip install -e .
          pip list

      - name: Run Python regression tests (serial)
        working-directory: test/regression
        run: python run.py

  python-regression-mpi:
    name: Python regression (MPI)
    runs-on: ubuntu-22.04
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip

      - name: Show environment info
        run: |
          pwd
          ls
          python --version
          pip --version

      - name: Set up MPI
        uses: mpi4py/setup-mpi@v1

      - name: Install mpi4py
        run: |
          pip install --upgrade pip
          pip install --no-binary=mpi4py mpi4py

      - name: Install MC/DC
        run: |
          pip install -e .
          pip list

      - name: Run Python regression tests (MPI)
        working-directory: test/regression
        run: |
          python run.py --mpiexec=4
          python run.py --mpiexec=16 --name=slab_reed_dd_3d
  
  numba-regression-serial:
    name: Numba regression (serial)
    runs-on: ubuntu-22.04
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip

      - name: Show environment info
        run: |
          pwd
          ls
          python --version
          pip --version

      - name: Set up MPI
        uses: mpi4py/setup-mpi@v1

      - name: Install mpi4py
        run: |
          pip install --upgrade pip
          pip install --no-binary=mpi4py mpi4py

      - name: Install MC/DC
        run: |
          pip install -e .
          pip list

      - name: Run Numba regression tests (serial)
        working-directory: test/regression
        run: python run.py --mode numba

  numba-regression-mpi:
    name: Numba regression (MPI)
    runs-on: ubuntu-22.04
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip

      - name: Show environment info
        run: |
          pwd
          ls
          python --version
          pip --version

      - name: Set up MPI
        uses: mpi4py/setup-mpi@v1

      - name: Install mpi4py
        run: |
          pip install --upgrade pip
          pip install --no-binary=mpi4py mpi4py

      - name: Install MC/DC
        run: |
          pip install -e .
          pip list

      - name: Run Numba regression tests (MPI)
        working-directory: test/regression
        run: |
          python run.py --mode numba --mpiexec=4
          python run.py --mode numba --mpiexec=16 --name=slab_reed_dd_3d
